"""first init db

Revision ID: 04c3c5c147b8
Revises: 3e9b2249a640
Create Date: 2017-10-28 17:16:22.241547

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '04c3c5c147b8'
down_revision = '3e9b2249a640'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('question5', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('question6', sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('students', 'question6')
    op.drop_column('students', 'question5')
    # ### end Alembic commands ###
