"""first init db

Revision ID: 3e9b2249a640
Revises: 53d6ba9cf8f2
Create Date: 2017-10-28 17:04:47.222465

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '3e9b2249a640'
down_revision = '53d6ba9cf8f2'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('day242', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('day243', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('day244', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('day251', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('day252', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('day253', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('day254', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('day261', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('day262', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('day263', sa.Boolean(), nullable=True))
    op.add_column('students', sa.Column('question1', sa.Integer(), nullable=True))
    op.add_column('students', sa.Column('question2', sa.Integer(), nullable=True))
    op.drop_column('students', 'whywants1')
    op.drop_column('students', 'whywants2')
    op.drop_column('students', 'day29')
    op.drop_column('students', 'day28')
    op.drop_column('students', 'day25')
    op.drop_column('students', 'photo')
    op.drop_column('students', 'day27')
    op.drop_column('students', 'day26')
    op.drop_column('students', 'what')
    op.drop_column('students', 'day30')
    op.drop_column('students', 'filename')
    op.drop_column('students', 'question5')
    op.drop_column('students', 'intro')
    op.drop_column('students', 'day291')
    op.drop_column('students', 'why')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('students', sa.Column('why', mysql.TEXT(), nullable=True))
    op.add_column('students', sa.Column('day291', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('intro', mysql.TEXT(), nullable=True))
    op.add_column('students', sa.Column('question5', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('filename', mysql.TEXT(), nullable=True))
    op.add_column('students', sa.Column('day30', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('what', mysql.TEXT(), nullable=True))
    op.add_column('students', sa.Column('day26', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('day27', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('photo', mysql.TEXT(), nullable=True))
    op.add_column('students', sa.Column('day25', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('day28', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('day29', mysql.TINYINT(display_width=1), autoincrement=False, nullable=True))
    op.add_column('students', sa.Column('whywants2', mysql.TEXT(), nullable=True))
    op.add_column('students', sa.Column('whywants1', mysql.TEXT(), nullable=True))
    op.drop_column('students', 'question2')
    op.drop_column('students', 'question1')
    op.drop_column('students', 'day263')
    op.drop_column('students', 'day262')
    op.drop_column('students', 'day261')
    op.drop_column('students', 'day254')
    op.drop_column('students', 'day253')
    op.drop_column('students', 'day252')
    op.drop_column('students', 'day251')
    op.drop_column('students', 'day244')
    op.drop_column('students', 'day243')
    op.drop_column('students', 'day242')
    # ### end Alembic commands ###
